# Mostly copied from https://docs.github.com/en/actions/automating-builds-and-tests/building-and-testing-java-with-ant
# zlatinb

name: Java CI

on: [push]

permissions:
  contents: read
  pages: write
  id-token: write

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: GetText
        run: sudo apt install gettext
      - uses: actions/checkout@v4
      - name: Set up JDK 8
        uses: actions/setup-java@v4
        with:
          java-version: '8'
          distribution: 'temurin'
      - name : Generate override.properties
        run: |
          rm -f override.properties
          echo "build.built-by=GitHub Actions" >> override.properties
          echo "noExe=true" >> override.properties
      - name: build with Gradle
        run: |
          ./gradlew assembleDebug
          find . -name '*.apk'

      #- name: Upload installer.jar
      #  uses: actions/upload-artifact@v4
      #  with:
      #    name: I2P-install.jar-${{ github.sha }}
      #    path: install.jar
