# Mostly copied from https://docs.github.com/en/actions/automating-builds-and-tests/building-and-testing-java-with-ant
# zlatinb

name: Java CI

on: [push]

permissions:
  contents: read
  pages: write
  id-token: write

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: GetText
        run: sudo apt install gettext git
      - uses: actions/checkout@v4
      - name: Set up JDK 11
        uses: actions/setup-java@v4
        with:
          java-version: '11'
          distribution: 'temurin'
      - name : Generate override.properties
        run: |
          rm -f override.properties
          echo "build.built-by=GitHub Actions" >> override.properties
          echo "noExe=true" >> override.properties
      - name: build with Gradle
        run: |
          echo "i2psrc=$HOME/i2p.i2p" > routerjars/local.properties
          git clone https://github.com/i2p/i2p.i2p "$HOME/i2p.i2p"
          ./gradlew assembleDebug
          find . -name '*.apk'

      #- name: Upload installer.jar
      #  uses: actions/upload-artifact@v4
      #  with:
      #    name: I2P-install.jar-${{ github.sha }}
      #    path: install.jar
  trunk:
    runs-on: ubuntu-latest

    steps:
      - name: GetText
        run: sudo apt install gettext git
      - uses: actions/checkout@v4
      - name: Set up JDK 11
        uses: actions/setup-java@v4
        with:
          java-version: '11'
          distribution: 'temurin'
      - name : Generate override.properties
        run: |
          rm -f override.properties
          echo "build.built-by=GitHub Actions" >> override.properties
          echo "noExe=true" >> override.properties
          echo "I2P_VERSION=2.4.0-1" >> override.properties
          echo "I2P_ANDROID_VERSION=2.4.0-1" >> override.properties
      - name: build with Gradle
        run: |
          echo "i2psrc=$HOME/i2p.i2p" > routerjars/local.properties
          git clone https://github.com/i2p/i2p.i2p "$HOME/i2p.i2p"
          cd i2p.i2p && ./installer/resources/maven-dev-release.sh 1
          ./gradlew assembleDebug
          find . -name '*.apk'

      #- name: Upload installer.jar
      #  uses: actions/upload-artifact@v4
      #  with:
      #    name: I2P-install.jar-${{ github.sha }}
      #    path: install.jar
