# Mostly copied from https://docs.github.com/en/actions/automating-builds-and-tests/building-and-testing-java-with-ant
# zlatinb

name: Java Signed CI

on: [push]

permissions:
  contents: read
  pages: write
  id-token: write

jobs:
  build-signed:
    runs-on: ubuntu-latest
    steps:
      - name: GetText
        run: sudo apt install gettext git
      - uses: actions/checkout@v4
      - name: Set up JDK 11
        uses: actions/setup-java@v4
        with:
          java-version: '11'
          distribution: 'temurin'
      - name: Generate override.properties
        env:
          DEV_SIGNING_KEY=${{ secrets.DEV_SIGNING_KEY }}
          DEV_PASSWORD=${{ secrets.DEV_PASSWORD }}
        run: |
          rm -f override.properties
          mv etc/github.gradle.properties gradle.properties
          mv etc/github.signing.properties signing.properties
          base64 -d $DEV_SIGNING_KEY > /home/user/keystores/android-release.keystore
          echo "KEY_ALIAS=mykey" >> signing.properties
          echo "KEY_PASSWORD=$DEV_PASSWORD" >> signing.properties
          echo "build.built-by=GitHub Actions" >> override.properties
          echo "noExe=true" >> override.properties
      - name: build with Gradle
        run: |
          echo "i2psrc=$HOME/i2p.i2p" > routerjars/local.properties
          git clone -b i2p-2.4.0 https://github.com/i2p/i2p.i2p "$HOME/i2p.i2p"
          ./gradlew assembleRelease
          find . -name '*.apk'
      - name: Upload i2p-debug-${{ github.sha }}.apk
        uses: actions/upload-artifact@v4
        with:
          name: i2p-debug.apk
          path: ./app/build/outputs/apk/free/debug/app-free-debug.apk

  trunk-signed:
    runs-on: ubuntu-latest
    steps:
      - name: GetText
        run: sudo apt install gettext git
      - uses: actions/checkout@v4
      - name: Set up JDK 11
        uses: actions/setup-java@v4
        with:
          java-version: '11'
          distribution: 'temurin'
      - name: Generate override.properties
        env:
          DEV_SIGNING_KEY=${{ secrets.DEV_SIGNING_KEY }}
          DEV_PASSWORD=${{ secrets.DEV_PASSWORD }}
        run: |
          rm -f override.properties
          echo "build.built-by=GitHub Actions" >> override.properties
          echo "noExe=true" >> override.properties
          mv etc/github.gradle.properties gradle.properties
          mv etc/github.signing.properties signing.properties
          base64 -d $DEV_SIGNING_KEY > /home/user/keystores/android-release.keystore
          echo "KEY_ALIAS=mykey" >> signing.properties
          echo "KEY_PASSWORD=$DEV_PASSWORD" >> signing.properties
          grep -v I2P_ gradle.properties > gradle.properties.update
          echo "I2P_VERSION=2.4.0-1" >> gradle.properties.update
          echo "I2P_ANDROID_VERSION=2.4.0-1" >> gradle.properties.update
          cp -v gradle.properties.update gradle.properties
      - name: build with Gradle
        run: |
          echo "i2psrc=$HOME/i2p.i2p" > routerjars/local.properties
          git clone -b master https://github.com/i2p/i2p.i2p "$HOME/i2p.i2p"
          bash -c "cd $HOME/i2p.i2p && ./installer/resources/maven-dev-release.sh 1"
          ./gradlew assembleRelease
          find . -name '*.apk'
      - name: Upload i2p-debug-${{ github.sha }}.apk
        uses: actions/upload-artifact@v4
        with:
          name: i2p-debug-trunk-${{ github.sha }}.apk
          path: ./app/build/outputs/apk/free/debug/app-free-debug.apk
